// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dtssqsssqbsilbowgqlm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR0c3Nxc3NzcWJzaWxib3dncWxtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3NjQ2NjUsImV4cCI6MjA3MzM0MDY2NX0.dybVoS91MCOu1gEPDp0nvDy-hWLjeQnZ_PuT8dNclD8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});